const plugin = require("tailwindcss/plugin");
module.exports = {
  darkMode: "class",
  purge: {
    content: ["./src/**/*.vue"],
  },
  corePlugins: [
    process.env.UNI_PLATFORM === "h5" ? "preflight" : "container",
    "container",
    "alignContent",
    "alignItems",
    "backgroundColor",
    "backgroundPosition",
    "backgroundRepeat",
    "backgroundSize",
    "borderColor",
    "borderRadius",
    "borderStyle",
    "borderWidth",
    "boxSizing",
    "clear",
    "cursor",
    "display",
    "fill",
    "flex",
    "flexDirection",
    "flexGrow",
    "flexShrink",
    "flexWrap",
    "fontSize",
    "fontWeight",
    "height",
    "inset",
    "justifyItems",
    "justifyContent",
    "lineHeight",
    "margin",
    "maxHeight",
    "maxWidth",
    "minHeight",
    "minWidth",
    "objectFit",
    "objectPosition",
    "opacity",
    "overflow",
    "position",
    "padding",
    "placeholderColor",
    "placeholderOpacity",
    "rotate",
    "scale",
    "tableLayout",
    "textAlign",
    "textColor",
    "textDecoration",
    "textOverflow",
    "textTransform",
    "transform",
    "transformOrigin",
    "transitionDelay",
    "transitionDuration",
    "transitionProperty",
    "transitionTimingFunction",
    "translate",
    "userSelect",
    "verticalAlign",
    "visibility",
    "whitespace",
    "width",
    "wordBreak",
    "zIndex",
  ],
  variants: {
    accessibility: [],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: ["dark", "active", "disabled"],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: [],
    cursor: [],
    display: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: [],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: ["disabled"],
    order: [],
    outline: [],
    overflow: [],
    padding: [],
    placeholderColor: [],
    pointerEvents: [],
    position: [],
    resize: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: ["dark", "active"],
    textDecoration: [],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: [],
  },
  theme: {
    screens: {
      sm: "640px",
      // => @media (min-width: 640px) { ... }
      md: "768px",
      // => @media (min-width: 768px) { ... }
      lg: "1024px",
      // => @media (min-width: 1024px) { ... }
      xl: "1280px",
    },
    spacing:
      process.env.UNI_PLATFORM !== "h5"
        ? {
            0: "0rpx",
            px: "2rpx",
            1: "8rpx",
            2: "16rpx",
            3: "24rpx",
            4: "32rpx",
            5: "40rpx",
            6: "48rpx",
            7: "56rpx",
            8: "64rpx",
            9: "72rpx",
            10: "80rpx",
            11: "84rpx",
            12: "96rpx",
            14: "112rpx",
            16: "128rpx",
            20: "160rpx",
            24: "192rpx",
            28: "224rpx",
            32: "256rpx",
            36: "288rpx",
            40: "320rpx",
            44: "352rpx",
            48: "384rpx",
            52: "416rpx",
            56: "448rpx",
            60: "480rpx",
            64: "512rpx",
            72: "576px",
            80: "640rpx",
            96: "768rpx",
          }
        : {
            px: "1px",
            0: "0px",
            1: "0.25rem",
            2: "0.5rem",
            3: "0.75rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            7: "1.75rem",
            8: "2rem",
            9: "2.25rem",
            10: "2.5rem",
            11: "2.75rem",
            12: "3rem",
            14: "3.5rem",
            16: "4rem",
            20: "5rem",
            24: "6rem",
            28: "7rem",
            32: "8rem",
            36: "9rem",
            40: "10rem",
            44: "11rem",
            48: "12rem",
            52: "13rem",
            56: "14rem",
            60: "15rem",
            64: "16rem",
            72: "18rem",
            80: "20rem",
            96: "24rem",
          },
    fontSize:
      process.env.UNI_PLATFORM !== "h5"
        ? {
            xs: ["24rpx", { lineHeight: "32rpx" }],
            sm: ["28rpx", { lineHeight: "40rpx" }],
            base: ["32rpx", { lineHeight: "48rpx" }],
            lg: ["36rpx", { lineHeight: "56rpx" }],
            xl: ["40rpx", { lineHeight: "56rpx" }],
            "2xl": ["48rpx", { lineHeight: "64rpx" }],
            "3xl": ["60rpx", { lineHeight: "72rpx" }],
            "4xl": ["72rpx", { lineHeight: "80rpx" }],
            "5xl": ["96rpx", { lineHeight: "1" }],
            "6xl": ["120rpx", { lineHeight: "1" }],
            "7xl": ["144rpx", { lineHeight: "1" }],
            "8xl": ["192rpx", { lineHeight: "1" }],
            "9xl": ["288rpx", { lineHeight: "1" }],
          }
        : {
            xs: ["0.75rem", { lineHeight: "1rem" }],
            sm: ["0.875rem", { lineHeight: "1.25rem" }],
            base: ["1rem", { lineHeight: "1.5rem" }],
            lg: ["1.125rem", { lineHeight: "1.75rem" }],
            xl: ["1.25rem", { lineHeight: "1.75rem" }],
            "2xl": ["1.5rem", { lineHeight: "2rem" }],
            "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
            "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
            "5xl": ["3rem", { lineHeight: "1" }],
            "6xl": ["3.75rem", { lineHeight: "1" }],
            "7xl": ["4.5rem", { lineHeight: "1" }],
            "8xl": ["6rem", { lineHeight: "1" }],
            "9xl": ["8rem", { lineHeight: "1" }],
          },
    minHeight: {
      0: "0rpx",
      full: "100%",
      screen: "100vh",
    },
    outline: {
      none: ["4rpx solid transparent", "4rpx"],
      white: ["4rpx dotted white", "4rpx"],
      black: ["4rpx dotted black", "4rpx"],
    },
    extend: {},
  },
  plugins: [
    plugin(function({ addComponents }) {
      const buttons = {
        ".shadow": {
          boxShadow:
            "0 2rpx 6rpx 0 rgba(0, 0, 0, 0.1), 0 2rpx 4rpx 0 rgba(0, 0, 0, 0.06)",
        },
        ".shadow-lg": {
          boxShadow:
            "0 20rpx 30rpx -6rpx rgba(0, 0, 0, 0.1), 0 8rpx 12rpx -4rpx rgba(0, 0, 0, 0.05)",
        },
      };

      addComponents(buttons);
    }),
  ],
};
