module.exports = {
  darkMode: false,
  purge: {
    content: ["./src/**/*.vue"],
  },
  corePlugins: [
    "alignContent",
    "alignItem",
    "backgroundColor",
    "backgroundOpacity",
    "backgroundPosition",
    "backgroundRepeat",
    "backgroundSize",
    "borderColor",
    "borderRadius",
    "borderStyle",
    "borderWidth",
    "boxShadow",
    "boxSizing",
    "clear",
    "cursor",
    "display",
    "fill",
    "flex",
    "flexDirection",
    "flexGrow",
    "flexShrink",
    "flexWrap",
    "fontSize",
    "fontWeight",
    "height",
    "inset",
    "justifyItems",
    "lineHeight",
    "margin",
    "maxHeight",
    "maxWidth",
    "minHeight",
    "minWidth",
    "objectFit",
    "objectPosition",
    "opacity",
    "overflow",
    "padding",
    "placeholderColor",
    "placeholderOpacity",
    "rotate",
    "scale",
    "tableLayout",
    "textAlign",
    "textColor",
    "textDecoration",
    "textOverflow",
    "textTransform",
    "transform",
    "transformOrigin",
    "transitionDelay",
    "transitionDuration",
    "transitionProperty",
    "transitionTimingFunction",
    "translate",
    "userSelect",
    "verticalAlign",
    "visibility",
    "whitespace",
    "width",
    "wordBreak",
    "zIndex",
  ],
  variants: {
    accessibility: [],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: [],
    cursor: [],
    display: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: [],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    order: [],
    outline: [],
    overflow: [],
    padding: [],
    placeholderColor: [],
    pointerEvents: [],
    position: [],
    resize: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: [],
    textDecoration: [],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: [],
  },
  plugins: [],
  theme: {
    spacing: {
      0: "0rpx",
      px: "2rpx",
      1: "4rpx",
      2: "8rpx",
      3: "12rpx",
      4: "16rpx",
      5: "20rpx",
      6: "24rpx",
      7: "28rpx",
      8: "32rpx",
      9: "36rpx",
      10: "40rpx",
      11: "44rpx",
      12: "48rpx",
      14: "56rpx",
      16: "64rpx",
      20: "80rpx",
      24: "96rpx",
      28: "112rpx",
      32: "128rpx",
      36: "144rpx",
      40: "160rpx",
      44: "176rpx",
      48: "192rpx",
      52: "108rpx",
      56: "224rpx",
      60: "240rpx",
      64: "256rpx",
      72: "288rpx",
      80: "320rpx",
      96: "384rpx",
    },
    fontSize: {
      xs: ["24rpx", { lineHeight: "32rpx" }],
      sm: ["28rpx", { lineHeight: "40rpx" }],
      base: ["32rpx", { lineHeight: "48rpx" }],
      lg: ["36rpx", { lineHeight: "56rpx" }],
      xl: ["40rpx", { lineHeight: "56rpx" }],
      "2xl": ["48rpx", { lineHeight: "64rpx" }],
      "3xl": ["60rpx", { lineHeight: "72rpx" }],
      "4xl": ["72rpx", { lineHeight: "80rpx" }],
      "5xl": ["96rpx", { lineHeight: "1" }],
      "6xl": ["120rpx", { lineHeight: "1" }],
      "7xl": ["144rpx", { lineHeight: "1" }],
      "8xl": ["192rpx", { lineHeight: "1" }],
      "9xl": ["288rpx", { lineHeight: "1" }],
    },
    minHeight: {
      0: "0rpx",
      full: "100%",
      screen: "100vh",
    },
    outline: {
      none: ["4rpx solid transparent", "4rpx"],
      white: ["4rpx dotted white", "4rpx"],
      black: ["4rpx dotted black", "4rpx"],
    },
    extend: {},
  },
};
